export const AuthActionType = {
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAIL : "SIGNUP_FAIL" ,
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_FAIL : "LOGIN_FAIL",
    LOGOUT_SUCCESS : "LOGOUT_SUCCESS",
    LOGOUT_FAIL : "LOGOUT_FAIL",
    PROFILE_COMPLETION_SUCCESS : "PROFILE_COMPLETION_SUCCESS",
    PROFILE_COMPLETION_FAIL : "PROFILE_COMPLETION_FAIL"
}

